services:
  keycloak:
    build:
      context: .
      args:
        KEYCLOAK_VERSION: ${KEYCLOAK_VERSION:-26.2.5}
        KEYCLOAK_VARIANT: ${KEYCLOAK_VARIANT:-generic}
    ports:
      - ${KEYCLOAK_PORT:-10079}:8443
    environment:
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: kcpassword
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME:-keycloak}
      KC_BOOTSTRAP_ADMIN_USERNAME: kcadmin
      KC_BOOTSTRAP_ADMIN_PASSWORD: kcadmin
  db:
    image: ${REGISTRY_DOCKER_HUB:-docker.io}/postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: kcpassword
      POSTGRES_DB: keycloak
