apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dbildungs-iam.fullname" . }}-keycloak
  labels:
    {{- include "dbildungs-iam.selectorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dbildungs-iam.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "dbildungs-iam.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "dbildungs-iam.fullname" . }}-keycloak-container
          image: {{ .Values.keycloakImage }}
          args:
            - start-dev
            - "--import-realm"
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_PROXY
              value: "edge"
          volumeMounts:
            - mountPath: "/opt/keycloak/data/import"
              name: "realm-config"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: realm-config
          secret:
            secretName: {{ include "dbildungs-iam.secretName" . }}
