apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.configmap" . }}
  labels: 
    app.kubernetes.io/name: {{ template "common.names.releasename" . }}
data:
  db-name: {{ .Values.database.name }}