{{- $frontendHost := (index (lookup "networking.k8s.io/v1" "Ingress" .Release.Namespace "spsh-client-ingress").spec.rules 0).host }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-keycloak-deployment
  labels:
    app.kubernetes.io/name: dbildungs-iam
spec:
  selector:
    matchLabels:
      layer: dbildungs-iam-keycloak
  replicas: 1
  template:
    metadata:
      name: dbildungs-iam-keycloak
      labels:
        layer: dbildungs-iam-keycloak
    spec:
      containers:
        - name: dbildungs-iam-keycloak
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          securityContext:
            allowPrivilegeEscalation: false
          # Workaround until we figure out the correct parameters          
          args:            
            - "--cache"
            - "local"
            - "--hostname"
            - "{{ .Values.keycloakHostname }}"
            - "--import-realm"
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key:  admin-user
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key:  admin-password
            - name: KC_PROXY
              value: "edge"
            - name: DB_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: db-url
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: db-name
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: db-username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: db-password
            - name: KC_DB_URL
              value: "jdbc:$(DB_BASE_URL)$(DB_NAME)"
            - name: KC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: keycloak-clientSecret
            - name: KC_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: keycloak-adminSecret
            - name: KC_ROOT_URL
              value: "https://{{$frontendHost}}"
          volumeMounts:
           - mountPath: "/opt/keycloak/data/import"
             name: "realm-config"
             readOnly: true
      restartPolicy: Always
      volumes:
        - name: realm-config
          secret:
            secretName: realm-config-secret