apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dbildungscloud-iam-keycloak.fullname" . }}
  labels:
    {{- include "dbildungscloud-iam-keycloak.selectorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dbildungscloud-iam-keycloak.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "dbildungscloud-iam-keycloak.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: keycloak  # Simplified container name
          image: {{ .Values.keycloakImage }}
          args:
            - start-dev
            - "--import-realm"
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              value: admin  # Note: I guess , it's best to use a secret for admin credentials
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin  # Note:  i guess, it's best to use a secret for admin credentials
            - name: KC_PROXY
              value: "edge"
          volumeMounts:
            - mountPath: "/opt/keycloak/data/import"
              name: "realm-config"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: realm-config
          secret:
            secretName: {{ include "dbildungscloud-iam-keycloak.secretName" . }}
