apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.secret" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  realm-spsh.json: |-
    {{.Files.Get "dev-realm-spsh.json" | b64enc}}