{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  {{- if .Values.auth.existingSecret }}
  name: {{ .Values.auth.existingSecret }}
  {{- end }}
  {{- if not .Values.auth.existingSecret }}
  name: {{ .Values.auth.name }}
  {{- end }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  admin-password: {{ .Values.auth.admin_password }}
  admin-user: {{ .Values.auth.admin_user }}
  db-host: {{ .Values.database.db_host }}
  db-password: {{ .Values.database.db_password }}
  db-username: {{ .Values.database.db_username }}
  keycloak-adminSecret: {{ .Values.auth.keycloak_adminSecret }}
  keycloak-clientSecret: {{ .Values.auth.keycloak_clientSecret }}
{{- end }}