{{- $dbiamSecrets := (lookup "v1" "Secret" .Release.Namespace .Values.secrets.name )}}
{{- if not  $dbiamSecrets }}
{{- fail (print "No secret in namespace " .Release.Namespace " under " .Values.secrets.name " deployment cannot continue") }}
{{- end }}
{{- $adminSecret := index $dbiamSecrets.data "keycloak.adminSecret" | b64dec }}
{{- $clientSecret := index $dbiamSecrets.data "keycloak.clientSecret" | b64dec }}
{{- if not $adminSecret }}
{{- fail "Admin secret not set"}}
{{- end }}
{{- if not $clientSecret }}
{{- fail "Client secret not set"}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: realm-config-secret
type: Opaque
data:
  realm-spsh.json: |-
      {{.Files.Get "dev-realm-spsh.json" | replace "___CLIENT_SECRET___" $clientSecret | replace "___ADMIN_SECRET___" $adminSecret | b64enc}}