apiVersion: v1
kind: Service
metadata:
  name: {{ include "dbildungscloud-iam-keycloak.serviceName" . }}
  labels:
    {{- include "dbildungscloud-iam-keycloak.selectorLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "dbildungscloud-iam-keycloak.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: web
  type: ClusterIP

