apiVersion: v1
kind: Service
metadata:
  name: {{ include "dbildungscloud-iam-keycloak.serviceName" . }}
  labels:
    {{- include "dbildungscloud-iam-keycloak.selectorLabels" . | nindent 4 }}
spec:
  ports:
    - name: {{ include "dbildungscloud-iam-keycloak.portName" . }}
      port: 80
      targetPort: {{ include "dbildungscloud-iam-keycloak.portName" . }}
  selector:
    {{- include "dbildungscloud-iam-keycloak.selectorLabels" . | nindent 6 }}
  type: ClusterIP
