apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.name" . }}
  namespace: {{ template "common.names.namespace" . }}
  labels: 
    {{- include "common.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.configMapData }}
  {{ $key }}: {{ quote $value }}
{{- end }}