apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.name" . }}
  namespace: {{ template "common.names.namespace" . }}
  labels: 
    {{- include "common.labels" . | nindent 4 }}
data:
  DB_NAME: "{{ .Values.database.name }}"
  # KC_DB_USERNAME: "$(DB_NAME)" # this is only true for staging
  KC_DB_URL: "jdbc:postgresql://$(DB_HOST)/$(DB_NAME)"
  KC_ROOT_URL: "https://{{ .Values.frontendHostname }}"
{{- range $key, $value := .Values.configMapData }}
  {{ $key }}: {{ quote $value }}
{{- end }}