apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.name" . }}
  namespace: {{ template "common.names.namespace" . }}
  labels: 
    {{- include "common.labels" . | nindent 4 }}
data:
  DB_NAME: "{{ .Values.database.name }}"
  KC_DB_USERNAME: "{{ .Values.database.username }}"
  KC_ROOT_URL: "https://{{ .Values.frontendHostname }}"
  KC_PROXY: "edge"
  KEYCLOAK_ADMIN: admin
  KC_SCHOOLSH_CLIENT_ROOT_URL: "{{ .Values.school_sh.rootUrl }}"
  KC_HTTP_MANAGEMENT_PORT: "8090"
  STATUS_URL: "{{ .Values.status.url }}"