apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.names.name" . }}
  namespace: {{ template "common.names.namespace" . }}
  labels:
  {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "common.names.name" . }}
      app.kubernetes.io/component: keycloak
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: keycloak
    spec:
      automountServiceAccountToken: false
      restartPolicy: {{ default "Always" .Values.restartPolicy }}
      containers:
        - name: {{ template "common.names.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }} 
          {{- if .command }}
          command:
            {{- toYaml .command | nindent 16 }}
          {{- end }}
          args:
            - "--cache"
            - "local"
            - "--hostname"
            - "{{ tpl .Values.keycloakHostname . }}" 
            - "--import-realm"
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          ports:
            {{- range .Values.containerPorts }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
            {{- end }}
          startupProbe: {{- omit .Values.startupProbe "enabled" | toYaml | nindent 12 }}
          livenessProbe: {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          readinessProbe: {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          env:
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default .Values.auth.existingSecret .Values.auth.secretName }}
                  key: admin-password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ default .Values.auth.existingSecret .Values.auth.secretName }}
                  key: db-host
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ default .Values.auth.existingSecret .Values.auth.secretName }}
                  key: db-username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default .Values.auth.existingSecret .Values.auth.secretName }}
                  key: db-password
            - name: KC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ default .Values.auth.existingSecret .Values.auth.secretName }}
                  key: keycloak-clientSecret
            - name: KC_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ default .Values.auth.existingSecret .Values.auth.secretName }}
                  key: keycloak-adminSecret
            - name: KC_ITSLEARNING_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ default .Values.auth.existingSecret .Values.auth.secretName }}
                  key: keycloak-itslearning-clientSecret
            - name: PI_BASE_URL
              valueFrom:
                secretKeyRef:
                    name: {{ default .Values.auth.existingSecret .Values.auth.secretName }}
                    key: pi-base-url
            - name: PI_ADMIN_USER
              valueFrom:
                secretKeyRef:
                    name: {{ default .Values.auth.existingSecret .Values.auth.secretName }}
                    key: pi-admin-user
            - name: PI_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: {{ default .Values.auth.existingSecret .Values.auth.secretName }}
                    key: pi-admin-password
            - name: PI_USER_RESOLVER
              valueFrom:
                secretKeyRef:
                    name: {{ default .Values.auth.existingSecret .Values.auth.secretName }}
                    key: pi-user-resolver
            - name: PI_REALM
              valueFrom:
                secretKeyRef:
                    name: {{ default .Values.auth.existingSecret .Values.auth.secretName }}
                    key: pi-user-realm
            - name: KC_OX_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ default .Values.auth.existingSecret .Values.auth.secretName }}
                  key: keycloak-ox-clientSecret
            - name: KC_DB_URL
              value: "jdbc:postgresql://$(DB_HOST)/$(DB_NAME)"
            {{- if .Values.extraEnvVars }}
            {{ toYaml .Values.extraEnvVars | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ template "common.names.name" . }}
          volumeMounts:
            - mountPath: "/opt/keycloak/data/import"
              name: realm-config
              readOnly: true
            {{- with .Values.extraVolumes }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: realm-config
          configMap:
            name: {{ .Values.realm.name }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}