apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "common.names.name" . }}
  namespace: {{ template "common.names.namespace" . }}
  labels: 
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    # theyshould be variable
spec:
  tls:
    - hosts:
        - {{ .Values.keycloakHostname  }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.keycloakHostname  }}
      http:
        paths:
          - path: {{ default "/" .path }}
            pathType: {{ .Values.ingress.pathType }}
            backend: 
              service:
                name: {{ template "common.names.name" . }}
                port:
                  number: {{ .Values.service.ports.http }}