{{- if .Values.keycloak.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "common.names.name" . }}
  namespace: {{ template "common.names.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  namespaceSelector:
    matchNames:
      - {{ include "common.names.namespace" . | quote }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "common.names.name" . }}
  endpoints:
    - port: {{ .Values.keycloak.serviceMonitor.port }}
      path: {{ .Values.keycloak.serviceMonitor.path }}
      interval: {{ .Values.keycloak.serviceMonitor.interval | default "30s" }}
{{- end }}
