apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.realm.name }}
  namespace: {{ template "common.names.namespace" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  realm-spsh.json: |-
    {{ .Files.Get .Values.realm.filepath | b64enc }}