{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.name }}
  namespace: {{ template "common.names.name" . }}
type: Opaque
data:
  admin-password: {{ .Values.auth.admin_password }}
  db-host: {{ .Values.database.db_host }}
  db-password: {{ .Values.database.db_password }}
  keycloak-adminSecret: {{ .Values.auth.keycloak_adminSecret }}
  keycloak-clientSecret: {{ .Values.auth.keycloak_clientSecret }}
{{- end }}