apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.name" . }}
  namespace: {{ template "common.names.namespace" . }}
  labels: 
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/layer: {{ .Values.selector.layer }}
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.http.enabled }}
    - name: http
      port: {{  .Values.service.ports.http }}
    {{- end }}