apiVersion: v2
name: dbildungscloud-iam-keycloak
version: 0.1.1

description: dbildungs-iam-keycloak
type: application

dependencies:
  - name: dbildungs-iam-keycloak
    version: "*"
    condition: keycloakEnabled

appVersion: "dbp-351"  # Set this to match your Docker image tag (see :https://github.com/dBildungsplattform/dbildungs-iam-keycloak/pkgs/container/dbildungs-iam)