replicaCount: 1
keycloakImage: "ghcr.io/dbildungsplattform/dbildungs-iam:sha-15679d4"  # for test purpose i set this image name
keycloakHostname: "keycloak.dev.spsh.dbildungsplattform.de"
keycloakPublic: false
