keycloakHostname: "keycloak.dev.spsh.dbildungsplattform.de"
secrets:
  name: keycloak
configmap:
  name: keycloak
image:
  repository: ghcr.io/dbildungsplattform/dbildungs-iam
  tag: ""
db:
  name: ""
frontendHostname: ""