name: Push Charts to helm-charts-registry on push to branch
on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'charts/**'
      - '.github/workflows/**'

concurrency:
  group: dbildungs-iam-keycloak-${{ github.event_name }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  scan:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-helm-kics.yaml@2.1.0
    permissions:
      contents: read
  release:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/chart-release.yaml@2.1.1
    secrets: inherit
    with:
      image_name: dbildungs-iam
      chart_name: dbildungscloud-iam-keycloak
      version_generation: ticket_from_branch_short_hash