# Push image to GHCR and Helm Chart to helm-charts-registry
name: Release Image and Helm Chart
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-?*' # matches v1.2.3 and v1.2.3-foobar

concurrency:
  group: dbp-keycloak-image-helm-chart
  cancel-in-progress: true

jobs:
  
  # Helm Chart
  scan_helm:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-helm-kics.yaml@5
    permissions:
      contents: read

  release_helm:
    needs: scan_helm
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/chart-release.yaml@7
    secrets: inherit
    with:
      chart_name: "dbp-keycloak"
      helm_chart_version_generation: specified 
      image_tag_generation: specified 
      helm_chart_version: "${{ github.ref_name }}"
      image_tag: "${{ github.ref_name }}"