name: "Build, upload and trivy scan image on push to main (Merge)"

on:
  push:
    branches:
      - main
jobs:
  build_image_on_push:
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/image-publish-trivy.yaml@1.0.0
    with:
      image_name: "dbildungs-iam"
      run_trivy_scan: true
      tag_generation: "commit_hash"
      add_latest_tag: true
      container_registry: "ghcr.io"