name: "Publish image to GHCR on push to main (Merge)"

on:
  push:
    branches:
      - main

concurrency:
  group: dbildungs-iam-keycloak-main
  cancel-in-progress: true

jobs:
  build_image_on_push:
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/image-publish-trivy.yaml@DBP-330-trivy-workflow
    with:
      image_name: "dbildungs-iam"
      run_trivy_scan: false
      tag_generation: "commit_hash"
      add_latest_tag: true
      container_registry: "ghcr.io"